version: '3.7'

networks:
  swarm_overlay:
    external: true
    name: swarm-overlay

services:

  traefik:
    image: traefik:1.7
    hostname: sc18.training.agaveplatform.org
    command: --configFile=/run/secrets/traefik_config_file
    secrets:
        - traefik_config_file
    networks:
      - swarm_overlay
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
      - target: 28443
        published: 28443
        protocol: tcp
        mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/agaveops/traefik/ssl:/ssl
    deploy:
      placement:
        constraints:
            - "node.role == manager"
            - "node.labels.leader == true"
      labels:
        - ops.service.type=proxy
        - ops.service.name=traefik
        - traefik.enable=true
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: rollback
        monitor: 10s
        max_failure_ratio: 0.3

secrets:
  traefik_config_file:
    file: "/home/agaveops/traefik/traefik.toml"
