global: {}
entryPoints:
  http:
    address: :80
  https:
    address: :443
providers:
  providersThrottleDuration: 2s
  docker:
    watch: true
    swarmMode: true
    swarmModeRefreshSeconds: 15s
log:
  level: DEBUG
certificatesResolvers:
  default:
    acme:
      email: ssl@sc18.training.agaveplatform.org
      storage: /ssl/acme.json
      httpChallenge:
        entryPoint: http
