###############################################################
# Local API management
# docker-compose.yml
#
# This example starts a traefik container on the local system
# and exposes it on an external network. This allows containers
# outside the stack to be dynamically discovered and proxied
# without having to spin up additional proxies. A static directory
# is also watched for configuration files pointing to persistent
# services used in my local environment.
#
# Notice that the Traefik config limits discovery of docker containers
# to those with a label matching "local.proxy.enabled=true". A
# separate
#
###############################################################

version: '3.7'

networks:
  traefik:
    external: true

services:
  traefik:
    image: traefik:v2.1
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--api.dashboard=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--providers.docker.constraints=Label(`local.proxy.enabled`,`true`)"
      - "--providers.file=true"
      - "--providers.file.directory=/config"
      - "--providers.file.watch=true"
      - "--entryPoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--entryPoints.grpc.address=:50052"
    ports:
      - 80:80
      - 443:443
      - 28080:8080
    restart: always
    volumes:
      - ./static-config:/config
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"


