global: {}
api:
  dashboard: true
  insecure: true

entryPoints:
  grpc:
    address: 50051

  http:
    address: :80
    middlewares:
      rate-limit:
        sourceCriterion:
          requestHeaderName: username
        inFlightReq:
          amount: 10
      https-only:
        redirectScheme:
          scheme: https

  https:
    address: :443
    middlewares:
      local-api-mgmt:
        chain:
          middlewares:
            - rate-limit
            - local-whitelist
            - inject-jwt

      rate-limit:
        sourceCriterion:
          requestHeaderName: username
        inFlightReq:
          amount: 10

      inject-auth:
        headers:
          customRequestHeaders:
            X-Script-Name: "test"
          customResponseHeaders:
            X-JWT-Assertion-Sandbox: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6Ik5tSm1PR1V4TXpabFlqTTJaRFJoTlRabFlUQTFZemRoWlRSaU9XRTBOV0kyTTJKbU9UYzFaQT09In0=.eyJpc3MiOiJ3c28yLm9yZy9wcm9kdWN0cy9hbSIsImV4cCI6MTQ1ODE1MDg1Njk0OCwiaHR0cDovL3dzbzIub3JnL2NsYWltcy9zdWJzY3JpYmVyIjoiQUdBVkUtUFJPRC9qc3R1YmJzIiwiaHR0cDovL3dzbzIub3JnL2NsYWltcy9hcHBsaWNhdGlvbmlkIjoiNTU1IiwiaHR0cDovL3dzbzIub3JnL2NsYWltcy9hcHBsaWNhdGlvbm5hbWUiOiJhYmFjbyIsImh0dHA6Ly93c28yLm9yZy9jbGFpbXMvYXBwbGljYXRpb250aWVyIjoiVW5saW1pdGVkIiwiaHR0cDovL3dzbzIub3JnL2NsYWltcy9hcGljb250ZXh0IjoiL2FjdG9ycy92MSIsImh0dHA6Ly93c28yLm9yZy9jbGFpbXMvdmVyc2lvbiI6Il9kZWZhdWx0X3YxIiwiaHR0cDovL3dzbzIub3JnL2NsYWltcy90aWVyIjoiVW5saW1pdGVkIiwiaHR0cDovL3dzbzIub3JnL2NsYWltcy9rZXl0eXBlIjoiUFJPRFVDVElPTiIsImh0dHA6Ly93c28yLm9yZy9jbGFpbXMvdXNlcnR5cGUiOiJBUFBMSUNBVElPTiIsImh0dHA6Ly93c28yLm9yZy9jbGFpbXMvZW5kdXNlciI6ImpzdHViYnNAY2FyYm9uLnN1cGVyIiwiaHR0cDovL3dzbzIub3JnL2NsYWltcy9lbmR1c2VyVGVuYW50SWQiOiItMTIzNCIsImh0dHA6Ly93c28yLm9yZy9jbGFpbXMvZW1haWxhZGRyZXNzIjoianN0dWJic0B0YWNjLnV0ZXhhcy5lZHUiLCJodHRwOi8vd3NvMi5vcmcvY2xhaW1zL2Z1bGxuYW1lIjoianN0dWJicyIsImh0dHA6Ly93c28yLm9yZy9jbGFpbXMvbGFzdG5hbWUiOiJqc3R1YmJzIiwiaHR0cDovL3dzbzIub3JnL2NsYWltcy9yb2xlIjoiSW50ZXJuYWwvQUdBVkUtUFJPRF9qc3R1YmJzX2VvZF90ZXN0X1BST0RVQ1RJT04sSW50ZXJuYWwvYWJhY28sSW50ZXJuYWwvQUdBVkUtUFJPRF9qc3R1YmJzX2FiYWNvX1BST0RVQ1RJT04sSW50ZXJuYWwvZXZlcnlvbmUsSW50ZXJuYWwvQUdBVkUtUFJPRF9qc3R1YmJzX0RlZmF1bHRBcHBsaWNhdGlvbl9QUk9EVUNUSU9OIn0=.VnFP6Het3sPj+R9eOmnyeX0D1x2gAfpdyWbFn0S/81h5HCtUx+ydmtwnNDtBU77+8p8cQrRwFgNL+GqlWX8wCa+zYJR8GWgZUZbGVZrFXmydipJkk9G9PqmycT2BS0eUG3Dg1DgOmcJ3NOGHI7/fSK7HFUuE9i0rhWvBI4UnRow="

      ipwhitelist:
        local-whitelist:
          sourceRange:
            - "127.0.0.1/32" # localhost
            - "192.168.10.100" # docker machine
            - "192.168.64.4" # minikube

providers:
 providersThrottleDuration: 2s
 docker:
   watch: true
   endpoint: unix:///var/run/docker.sock
   swarmModeRefreshSeconds: 15s
 file:
   directory: /providers
   watch: true

log:
  level: DEBUG
